//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingPeriod
    {
        public BillingPeriod()
        {
            this.Bills = new HashSet<Bill>();
        }
    
        public int BillingPeriodId { get; set; }
        public System.DateTime PeriodStartsFrom { get; set; }
        public string PeriodEndsAt { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual Company Company { get; set; }
    }
}
