//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingRate
    {
        public int BillingRateId { get; set; }
        public int BillingRateConfigId { get; set; }
        public Nullable<int> LimitTypeId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int CreteadBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual BillingRateConfig BillingRateConfig { get; set; }
        public virtual LimitType LimitType { get; set; }
    }
}
