//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillScheme
    {
        public BillScheme()
        {
            this.BillingRateConfigs = new HashSet<BillingRateConfig>();
            this.Devices = new HashSet<Device>();
        }
    
        public int BillSchemeId { get; set; }
        public int CompanyId { get; set; }
        public string BillSchemeName { get; set; }
        public string BillSchemeDescription { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual ICollection<BillingRateConfig> BillingRateConfigs { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
    }
}
