//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillId { get; set; }
        public int DeviceId { get; set; }
        public Nullable<int> BillingPeriodId { get; set; }
        public double TotalUnit { get; set; }
        public double TotalUnitCost { get; set; }
        public double TotalVAT { get; set; }
        public double Surcharge { get; set; }
        public double TotalCost { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual BillingPeriod BillingPeriod { get; set; }
        public virtual Device Device { get; set; }
    }
}
