//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommandValue
    {
        public int CommandValueId { get; set; }
        public int DeviceTypeId { get; set; }
        public int CommandId { get; set; }
        public string Value { get; set; }
    
        public virtual Command Command { get; set; }
        public virtual DeviceType DeviceType { get; set; }
    }
}
