//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Command
    {
        public Command()
        {
            this.CommandValues = new HashSet<CommandValue>();
        }
    
        public int CommandId { get; set; }
        public string CommandName { get; set; }
    
        public virtual ICollection<CommandValue> CommandValues { get; set; }
    }
}
