//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceProperty
    {
        public int DevicePropertyId { get; set; }
        public int DeviceId { get; set; }
        public string PropertyName { get; set; }
        public string PropertyParameter { get; set; }
        public string PropertyValue { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
