//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadScheme
    {
        public LoadScheme()
        {
            this.BillingRateConfigs = new HashSet<BillingRateConfig>();
        }
    
        public int LoadSchemeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string LoadSchemeName { get; set; }
        public string LoadSchemeDescription { get; set; }
        public double LoadFrom { get; set; }
        public double LoadTo { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual ICollection<BillingRateConfig> BillingRateConfigs { get; set; }
        public virtual Company Company { get; set; }
    }
}
