//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterProperty
    {
        public int DeviceId { get; set; }
        public int MeterPropertyId { get; set; }
        public double Voltage { get; set; }
        public double RealPower { get; set; }
        public double PowerFactor { get; set; }
        public double KWHR { get; set; }
        public System.DateTime TransmissionTime { get; set; }
        public Nullable<System.DateTime> LoggedAt { get; set; }
        public bool IsLatest { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public int CreatedBy { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual Device Device { get; set; }
    }
}
