//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartMeterEntities : DbContext
    {
        public SmartMeterEntities()
            : base("name=SmartMeterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<AppUser> AppUsers { get; set; }
        public DbSet<Bill> Bills { get; set; }
        public DbSet<BillingPeriod> BillingPeriods { get; set; }
        public DbSet<BillingRate> BillingRates { get; set; }
        public DbSet<BillingRateConfig> BillingRateConfigs { get; set; }
        public DbSet<BillScheme> BillSchemes { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Command> Commands { get; set; }
        public DbSet<CommandValue> CommandValues { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyUser> CompanyUsers { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Device> Devices { get; set; }
        public DbSet<DeviceProperty> DeviceProperties { get; set; }
        public DbSet<DeviceType> DeviceTypes { get; set; }
        public DbSet<DeviceTypeProperty> DeviceTypeProperties { get; set; }
        public DbSet<LimitType> LimitTypes { get; set; }
        public DbSet<LoadScheme> LoadSchemes { get; set; }
        public DbSet<MeterProperty> MeterProperties { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RolePermission> RolePermissions { get; set; }
        public DbSet<TimeScheme> TimeSchemes { get; set; }
        public DbSet<UserLog> UserLogs { get; set; }
        public DbSet<UserPermission> UserPermissions { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
    }
}
