//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMeter.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int UserId { get; set; }
        public System.DateTime LogInTime { get; set; }
        public Nullable<System.DateTime> LogOutTime { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
